export interface ServerFeed {
  name: string;
  url: string;
  lang?: string;
}

const AZ_FEEDS: ServerFeed[] = [
  { name: 'Report.az', url: 'https://report.az/rss' },
  { name: 'Oxu.az',    url: 'https://oxu.az/feed' },
  { name: 'Haqqin.az', url: 'https://haqqin.az/rss' },
];

export const VARIANT_FEEDS: Record<string, Record<string, ServerFeed[]>> = {
  full: {
    politics:        AZ_FEEDS,
    us:              AZ_FEEDS,
    europe:          AZ_FEEDS,
    middleeast:      AZ_FEEDS,
    africa:          AZ_FEEDS,
    latam:           AZ_FEEDS,
    asia:            AZ_FEEDS,
    energy:          AZ_FEEDS,
    gov:             AZ_FEEDS,
    thinktanks:      AZ_FEEDS,
    ai:              AZ_FEEDS,
    layoffs:         AZ_FEEDS,
    startups:        AZ_FEEDS,
    vcblogs:         AZ_FEEDS,
    regionalStartups: AZ_FEEDS,
    unicorns:        AZ_FEEDS,
    accelerators:    AZ_FEEDS,
    funding:         AZ_FEEDS,
    producthunt:     AZ_FEEDS,
    security:        AZ_FEEDS,
    policy:          AZ_FEEDS,
    hardware:        AZ_FEEDS,
    cloud:           AZ_FEEDS,
    dev:             AZ_FEEDS,
    github:          AZ_FEEDS,
    ipo:             AZ_FEEDS,
    finance:         AZ_FEEDS,
    tech:            AZ_FEEDS,
    crisis:          AZ_FEEDS,
  },
  tech: {
    tech:            AZ_FEEDS,
    ai:              AZ_FEEDS,
    startups:        AZ_FEEDS,
    vcblogs:         AZ_FEEDS,
    regionalStartups: AZ_FEEDS,
    unicorns:        AZ_FEEDS,
    accelerators:    AZ_FEEDS,
    security:        AZ_FEEDS,
    policy:          AZ_FEEDS,
    github:          AZ_FEEDS,
    funding:         AZ_FEEDS,
    cloud:           AZ_FEEDS,
    layoffs:         AZ_FEEDS,
    finance:         AZ_FEEDS,
    dev:             AZ_FEEDS,
    ipo:             AZ_FEEDS,
    producthunt:     AZ_FEEDS,
    hardware:        AZ_FEEDS,
    outages:         AZ_FEEDS,
  },
  finance: {
    finance:         AZ_FEEDS,
    markets:         AZ_FEEDS,
    forex:           AZ_FEEDS,
    bonds:           AZ_FEEDS,
    commodities:     AZ_FEEDS,
    crypto:          AZ_FEEDS,
    centralbanks:    AZ_FEEDS,
    economic:        AZ_FEEDS,
    ipo:             AZ_FEEDS,
    derivatives:     AZ_FEEDS,
    fintech:         AZ_FEEDS,
    regulation:      AZ_FEEDS,
    institutional:   AZ_FEEDS,
    analysis:        AZ_FEEDS,
    gccNews:         AZ_FEEDS,
  },
  commodity: {
    'commodity-news':    AZ_FEEDS,
    'gold-silver':       AZ_FEEDS,
    energy:              AZ_FEEDS,
    'mining-news':       AZ_FEEDS,
    'critical-minerals': AZ_FEEDS,
    'base-metals':       AZ_FEEDS,
    'mining-companies':  AZ_FEEDS,
    'supply-chain':      AZ_FEEDS,
    'commodity-regulation': AZ_FEEDS,
    markets:             AZ_FEEDS,
    finance:             AZ_FEEDS,
  },
  happy: {
    positive:        AZ_FEEDS,
    science:         AZ_FEEDS,
    nature:          AZ_FEEDS,
    inspiring:       AZ_FEEDS,
    community:       AZ_FEEDS,
  },
};

export const INTEL_SOURCES: ServerFeed[] = [];
